name: Intro

on: [workflow_dispatch, push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
      - run: echo "My variable is ${{ vars.variavel }}"
      - run: echo "My secret is ${{ secrets.segredo }}"
