name: On_push

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Helloooooooworls"
      - run: echo "My secret is ${{ secrets.SEGREDO }}"
      - run: echo "My variable is ${{ vars.VARIAVEL }}"

